### ISSUE TITLE
SOAL

### ISSUE THREAD

**Issue by rizkifreao** [rizkifreao/Kelompok5#4]
**User**
- [x]  1. User can see all list books 
- [x]  2. User can view one book
- [x]  3. User can order book/s #9 

**Admin**
- [x]  1. Admin can create a book  #8 
- [x]  2. Admin can delete a book #8
- [x]  3. Admin can update a book #8
